version: "1"

services:
  postgres:
    image: postgres
    container_name: money-saver-postgres
    ports:
      - "54323:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-money-saver
    volumes:
      - data_postgres:/var/lib/postgresql/data

volumes:
  data_postgres:
